add choosing the point with the highest variance of the predicitons
nuwanda57/RoboScientist pull request #14
Opened 2020-05-15 13:47 UTC by mishazybin

Поменял main, чтобы без копипаста можно было запускать все теории на всех средах с нужными генераторами.

2020-05-19 19:30 UTC, nuwanda57 requested changes

2020-05-19 19:30 UTC, nuwanda57 commented on theories/theory_multiple_nested_formulas.py
> +            self._all_models.append(single_theory)
тут точно не нужна копия?

2020-05-19 19:30 UTC, nuwanda57 commented on theories/theory_multiple_nested_formulas.py
> +                self._model = single_theory
тут точно не нужна копия?

2020-05-19 19:30 UTC, nuwanda57 commented on theories/theory_multiple_nested_formulas.py
> +    def __deepcopy__(self, memodict={}):
вроде это неправильно, нет?

2020-05-20 07:24 UTC, mishazybin commented on theories/theory_multiple_nested_formulas.py
> +            self._all_models.append(single_theory)
скорее всего, нужна

2020-05-20 07:24 UTC, mishazybin commented on theories/theory_multiple_nested_formulas.py
> +                self._model = single_theory
скорее всего, нужна

2020-05-20 09:53 UTC, nuwanda57 requested changes

2020-05-20 09:53 UTC, nuwanda57 commented on config.py
> +PROJECT_ROOT = '/home/zybinmikhail/Desktop/personal github projects/RoboScientist/'
баг:)

2020-05-20 09:53 UTC, nuwanda57 commented on theories/theory_master.py
> +class MasterTheory(base.TheoryBase):
А давай все же упомянем std в названии? (просто может быть другая "MasterTheory")

2020-05-20 09:53 UTC, nuwanda57 commented on theories/theory_master.py
> +    Class used for representing theories that themselves consist from multiple theories
Да, но это только часть описания, стоит написать, что она делает с этими теориями

2020-05-20 09:53 UTC, nuwanda57 commented on theories/theory_master.py
> +        new_obj._model = copy.deepcopy(self._model)
лучше pickle для модели, думаю

2020-05-23 18:48 UTC, nuwanda57 approved these changes

2020-05-23 18:48 UTC, nuwanda57 commented on theories/theory_master.py
> +    def __init__(self, *args, theories_with_params=[(theory_nested_formulas.TheoryNestedFormula, None) for i in range(10)]):
надо убрать дефолтный

2020-05-23 18:48 UTC, merged