add nested formulas
nuwanda57/RoboScientist pull request #8
Opened 2020-05-07 12:10 UTC by mishazybin

I modified the file `main.py`, so that it can launch either AI Feynman or nested formulas. Currently, there are no problems in the logs of nested formulas, but in the logs of AI Physicist there is an error  `2020-05-07 15:03:27 - rs.TheoryFeynman - ERROR: Unable to evaluate formula sin(x). MSE=1000`

2020-05-07 12:54 UTC, nuwanda57 requested changes

2020-05-07 12:54 UTC, nuwanda57 commented on learning_agent/robo_scientist.py
> -from copy import deepcopy
Нет, это удалять не надо.
Я сказала удалить только потому что ошибка была. Если она все еще осталась, надо с ней разобраться. Если удалить, то в результаты, которые мы складываем, будут меняться в процессе обучения.

2020-05-07 12:54 UTC, nuwanda57 commented on main.py
> +    elif using == "feynman":
не нужен if. Надо оставить компиляцию в любом случае.

2020-05-07 12:54 UTC, nuwanda57 commented on main.py
> +        theory_nested_formulas.TheoryNestedFormula: nested_formulas_dir
мне кажется, тебе это не нужно. Если не добавлять сюда теорию, то директория просто не будет меняться.

2020-05-07 12:54 UTC, nuwanda57 commented on main.py
> +    nested_formulas_dir = os.path.join(os.getcwd(), 'theories/nested_formulas/')
см ниже.

2020-05-07 12:54 UTC, nuwanda57 commented on main.py
> +def main(using="feynman"):
Не нужно тут аргумент. Давай просто обе теории проверять.

2020-05-07 12:54 UTC, nuwanda57 commented on main.py
> +    agent.explore_environment(env_1.Environment1(), theory, simple_generator.SimpleGenerator)
Вместо этого предлагаю так:

```
agent.explore_environment(env_1.Environment1(), theory_feynman.TheoryFeynman, simple_generator.SimpleGenerator)
print('\nAnswer:', agent.get_formula_for_exploration_key(rs.ExplorationKey(
        env=env_1.Environment1.__name__, theory=theory_feynman.TheoryFeynman.__name__)))	

agent.explore_environment(env_1.Environment1(), theory_nested_formulas.TheoryNestedFormula, simple_generator.SimpleGenerator)
print('\nAnswer:', agent.get_formula_for_exploration_key(rs.ExplorationKey(
        env=env_1.Environment1.__name__, theory=theory_nested_formulas.TheoryNestedFormula.__name__)))	       

```

2020-05-07 12:54 UTC, nuwanda57 commented on main.py
> +        theory = theory_nested_formulas.TheoryNestedFormula
не нужно определять theory. смотри комментарий ниже: будем обучать обе теории.

2020-05-07 12:54 UTC, nuwanda57 commented on theories/theory_nested_formulas.py
> +# import torch
убери, пожалуйста

2020-05-07 12:54 UTC, nuwanda57 commented on theories/theory_nested_formulas.py
> +        stdout = 'nested_formula_stdout.txt'
у тебя разве есть stdout?
В feynman я это добавила, потому что сам feynman на stdout пишет очень много ненужного. То есть я просто очистила stdout от дебажной информации. Так как это твоя теория, а не внешняя, то, если нужно что-то вывести, выводи сразу в файл, а не перенаправляй выход.

2020-05-07 12:54 UTC, nuwanda57 commented on theories/nested_formulas/nested_formula.py
> +def LearnFormula(X, y, optimizer_for_formula=torch.optim.Adam, device=torch.device("cpu"), n_init=1, max_iter=100,
вот это должно быть не отдельной функцией, а теорией.

2020-05-07 12:54 UTC, nuwanda57 commented on theories/nested_formulas/explore.py
> +def explore(n_variables=3, m_samples=1000, min_power=1, max_power=1, number_of_tested_formulas=10,
кажется, это нигде теорией не используется? Тогда это не нужно?

2020-05-07 14:04 UTC, mishazybin commented on main.py
> +    nested_formulas_dir = os.path.join(os.getcwd(), 'theories/nested_formulas/')
переделал

2020-05-07 14:04 UTC, mishazybin commented on main.py
> +        theory = theory_nested_formulas.TheoryNestedFormula
переделал

2020-05-07 14:04 UTC, mishazybin commented on theories/theory_nested_formulas.py
> +        stdout = 'nested_formula_stdout.txt'
переделал

2020-05-07 14:05 UTC, mishazybin commented on theories/nested_formulas/explore.py
> +def explore(n_variables=3, m_samples=1000, min_power=1, max_power=1, number_of_tested_formulas=10,
убрал

2020-05-07 14:06 UTC, mishazybin commented on learning_agent/robo_scientist.py
> -from copy import deepcopy
не знаю, как это исправить, я это гуглил, но пока не разобрался - это как-то связано с мультипроцессингом и обычно возникает у людей, когда они работают с керасом или тензорфлоу

2020-05-07 14:18 UTC, nuwanda57 reviewed
Супер!

2020-05-07 14:18 UTC, nuwanda57 commented on config.py
> +PROJECT_ROOT = '/home/zybinmikhail/Documents/personal github projects/RoboScientist'
надо убрать из коммита

2020-05-07 14:18 UTC, nuwanda57 commented on learning_agent/robo_scientist.py
> -from copy import deepcopy
Да, я тоже погуглила. Сейчас еще погуглю:)

2020-05-07 14:18 UTC, nuwanda57 commented on theories/theory_feynman.py
>  import os
а зачем изменения в этом файле?

2020-05-07 14:18 UTC, nuwanda57 commented on theories/theory_nested_formulas.py
> +# from auxiliary_functions import *
убери, пожалуйста. И не нужно import * делать.

2020-05-08 08:02 UTC, mishazybin commented on theories/theory_feynman.py
>  import os
Эти библиотеки в нем не используются

2020-05-11 11:43 UTC, merged